using System.Collections.Generic;
using System.Text;

using VimGitDiff.Git;

namespace VimGitDiff.Vim;

public sealed class VimScriptBuilder
{
    public string Build(DiffPlan plan)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\" generated by vim-git-diff");

        sb.AppendLine("silent! set diffopt+=algorithm:histogram");

        sb.AppendLine("silent! set diffopt+=linematch:60");

        sb.AppendLine("set nomore");

        sb.AppendLine("let s:vgd_script = expand('<sfile>:p')");

        var contentPaths = CollectContentPaths(plan);

        AppendCleanupAutocmd(sb, contentPaths);

        var first = true;

        for (var i = 0; i < plan.Files.Count; i++)
        {
            AppendFilePair(sb, plan, plan.Files[i], i, first);

            first = false;
        }

        sb.AppendLine("tabfirst");

        sb.AppendLine("if tabpagenr('$') > 1 | tabclose | endif");

        return sb.ToString();
    }

    private static List<string> CollectContentPaths(DiffPlan plan)
    {
        var paths = new List<string>();

        if (plan.ContentPaths == null)
        {
            return paths;
        }

        foreach (var path in plan.ContentPaths.Values)
        {
            paths.Add(path);
        }

        return paths;
    }

    private static void AppendCleanupAutocmd(StringBuilder sb, List<string> contentPaths)
    {
        sb.Append("let s:vgd_temps = [s:vgd_script");

        foreach (var path in contentPaths)
        {
            sb.Append(", ");

            sb.Append(VimStringLiteral.Quote(path));
        }

        sb.AppendLine("]");

        sb.AppendLine("autocmd VimLeave * silent! call map(s:vgd_temps, 'delete(v:val)')");
    }

    private void AppendFilePair(StringBuilder sb, DiffPlan plan, ChangedFile file, int fileIndex, bool isFirstTab)
    {
        var refA = plan.Refs.RefA;

        var refB = plan.Refs.RefB;

        var labelA = SideLabel.Build(file.DisplayPath, file.PathA, refA);

        var labelB = SideLabel.Build(file.DisplayPath, file.PathB, refB);

        var basenameA = Basename(file.PathA ?? file.DisplayPath);

        var basenameB = Basename(file.PathB ?? file.DisplayPath);

        sb.AppendLine("tabnew");

        AppendSide(sb, plan, refA, file.PathA, fileIndex, labelA, basenameA, isLeft: true);

        sb.AppendLine("vert new");

        AppendSide(sb, plan, refB, file.PathB, fileIndex, labelB, basenameB, isLeft: false);
    }

    private void AppendSide(
        StringBuilder sb,
        DiffPlan plan,
        string @ref,
        string? path,
        int fileIndex,
        string label,
        string basename,
        bool isLeft)
    {
        sb.AppendLine("enew");

        sb.AppendLine("setlocal buftype=nofile bufhidden=wipe noswapfile modifiable");

        if (path != null)
        {
            AppendReadCommand(sb, plan, @ref, path, fileIndex, isLeft);

            sb.AppendLine("silent! 1delete _");
        }

        sb.AppendLine("silent file " + VimFilenameEscaper.Escape(label));

        sb.AppendLine("silent! doautocmd BufRead " + VimFilenameEscaper.Escape(basename));

        sb.AppendLine("setlocal nomodified nomodifiable readonly");

        sb.AppendLine("diffthis");
    }

    private void AppendReadCommand(StringBuilder sb, DiffPlan plan, string @ref, string path, int fileIndex, bool isLeft)
    {
        if (@ref == GitRefSpec.WorkingTree)
        {
            var full = System.IO.Path.Combine(plan.RepoRoot, path.Replace('/', System.IO.Path.DirectorySeparatorChar));

            sb.AppendLine("silent 0read " + VimFilenameEscaper.Escape(full));

            return;
        }

        var contentPath = plan.ContentPaths?[(fileIndex, isLeft)]
            ?? throw new System.InvalidOperationException(
                $"missing extracted content for file {fileIndex} ({(isLeft ? "left" : "right")})");

        sb.AppendLine("silent 0read " + VimFilenameEscaper.Escape(contentPath));
    }

    private static string Basename(string path)
    {
        var slash = path.LastIndexOf('/');

        if (slash < 0)
        {
            return path;
        }

        return path.Substring(slash + 1);
    }
}
