using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

using VimGitDiff.Git;

namespace VimGitDiff.Vim;

public sealed class VimScriptBuilder
{
    private readonly bool _quoteForCmd;

    public VimScriptBuilder() : this(RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    {
    }

    public VimScriptBuilder(bool quoteForCmd)
    {
        _quoteForCmd = quoteForCmd;
    }

    public string Build(DiffPlan plan)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\" generated by vim-git-diff");

        sb.AppendLine("silent! set diffopt+=algorithm:histogram");

        sb.AppendLine("silent! set diffopt+=linematch:60");

        sb.AppendLine("set nomore");

        sb.AppendLine("let s:vgd_script = expand('<sfile>:p')");

        sb.AppendLine("autocmd VimLeave * silent! call delete(s:vgd_script)");

        var first = true;

        foreach (var file in plan.Files)
        {
            AppendFilePair(sb, plan, file, first);

            first = false;
        }

        sb.AppendLine("tabfirst");

        sb.AppendLine("if tabpagenr('$') > 1 | tabclose | endif");

        return sb.ToString();
    }

    private void AppendFilePair(StringBuilder sb, DiffPlan plan, ChangedFile file, bool isFirstTab)
    {
        var refA = plan.Refs.RefA;

        var refB = plan.Refs.RefB;

        var labelA = SideLabel.Build(file.DisplayPath, file.PathA, refA);

        var labelB = SideLabel.Build(file.DisplayPath, file.PathB, refB);

        var basenameA = Basename(file.PathA ?? file.DisplayPath);

        var basenameB = Basename(file.PathB ?? file.DisplayPath);

        if (isFirstTab)
        {
            sb.AppendLine("tabnew");
        }
        else
        {
            sb.AppendLine("tabnew");
        }

        AppendSide(sb, plan.RepoRoot, refA, file.PathA, labelA, basenameA, isLeft: true);

        sb.AppendLine("vert new");

        AppendSide(sb, plan.RepoRoot, refB, file.PathB, labelB, basenameB, isLeft: false);
    }

    private void AppendSide(
        StringBuilder sb,
        string repoRoot,
        string @ref,
        string? path,
        string label,
        string basename,
        bool isLeft)
    {
        sb.AppendLine("enew");

        sb.AppendLine("setlocal buftype=nofile bufhidden=wipe noswapfile modifiable");

        if (path != null)
        {
            AppendReadCommand(sb, repoRoot, @ref, path);

            sb.AppendLine("silent! 1delete _");
        }

        sb.AppendLine("silent file " + VimFilenameEscaper.Escape(label));

        sb.AppendLine("silent! doautocmd BufRead " + VimFilenameEscaper.Escape(basename));

        sb.AppendLine("setlocal nomodified nomodifiable readonly");

        sb.AppendLine("diffthis");
    }

    private void AppendReadCommand(StringBuilder sb, string repoRoot, string @ref, string path)
    {
        if (@ref == GitRefSpec.WorkingTree)
        {
            var full = System.IO.Path.Combine(repoRoot, path.Replace('/', System.IO.Path.DirectorySeparatorChar));

            sb.AppendLine("silent 0read " + VimFilenameEscaper.Escape(full));

            return;
        }

        var spec = @ref == GitRefSpec.Index ? ":" + path : @ref + ":" + path;

        var quoted = BuildShellCommand(repoRoot, spec);

        sb.AppendLine("silent 0read !" + quoted);
    }

    private string BuildShellCommand(string repoRoot, string spec)
    {
        if (_quoteForCmd)
        {
            return string.Join(' ', new[]
            {
                "git",
                "-C",
                VimShellQuoter.QuoteForCmd(repoRoot),
                "show",
                VimShellQuoter.QuoteForCmd(spec),
            });
        }

        return string.Join(' ', new[]
        {
            "git",
            "-C",
            VimShellQuoter.QuoteForPosix(repoRoot),
            "show",
            VimShellQuoter.QuoteForPosix(spec),
        });
    }

    private static string Basename(string path)
    {
        var slash = path.LastIndexOf('/');

        if (slash < 0)
        {
            return path;
        }

        return path.Substring(slash + 1);
    }
}
